### ISSUE TITLE
Turrets

### ISSUE THREAD

**Issue by paxorus** [Tristanibus/jsgame#7]
Once produced by a factory and placed by the player, a turret should automatically revolve and shoot at enemy objects within a radius but outside a certain radius (can't shoot enemies that are too close). It might prioritize the closest object or the object with the lowest health.

**Comment by Tristanibus** [comment]
wontfix: Missiles originate from center of turret.
Stop tracking robots when move out of range.
Sloppy +90 fix, do the math again.
Target the weakest enemy.
There is a rapid 180 or 360 when an enemy dies or a new enemy comes into view... check the math.

**Comment by paxorus** [comment]
- [x] Missiles originate from center of turret.
- [x] Stop tracking robots when move out of range.
- [x] Sloppy +90 fix, do the math again.
- [ ] Target the weakest enemy.
- [x] There is a rapid 180 or 360 when an enemy dies or a new enemy comes into view... check the math.
- [x] Fires at top-left corner.
- [ ] Only fires at robots.
